apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend-rs
  labels:
    app: backend
spec:
  replicas: 10
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container-nginx
        image: nginx